import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from '../components'
import { useSearch } from '../context/SearchContext'
import { or } from '../assets'

const Home = () => {
    const [loading, setLoading] = useState(false)
    const [allPosts, setAllPosts] = useState(null)

    const [searchText, setSearchText] = useState('')
    const [searchedResults, setSearchedResults] = useState(null)
    const [searchTimeout, setSearchTimeout] = useState(null)
    
    const { isSearchVisible } = useSearch();

        const fetchPosts = async () => {
            setLoading(true)

            try{
            const response = await fetch('https://orion-ai-sigma.vercel.app/api/v1/post',{
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                },
            })

            if(response.ok){
                const result = await response.json()

                setAllPosts(result.data.reverse())
            }

            }catch(error){
            alert(error)
            }finally{
            setLoading(false)
            }
        }
        useEffect(() => {
        fetchPosts()
    }, [])
    

    const RenderCards =  ({data, title})=>{
        if(data?.length > 0) {
        return data.map((post) => 
        <Card key={post._id} {...post}/>)
    }
    return(
        <h2 className='mt-5 font-bold text-[#6449ff]
        text-xl uppercase'>{title}</h2>
    )
}

const handleSearchChange = (e) => {
    clearTimeout(searchTimeout)
    setSearchText(e.target.value)

    setSearchTimeout(
    setTimeout(() => {
        const searchResults = allPosts.filter((item) => 
        item.name.toLowerCase().includes(searchText.toLowerCase()) ||
        item.prompt.toLowerCase().includes(searchText.toLowerCase()))

        setSearchedResults(searchResults)
    }, 500)
    )
}
    

  return (
    <section className='max-w-7x1 mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#ffffff] text-[32px] mt-[200px] sm:mt-[400px] md:mt-[500px] lg:mt-[600px] xl:mt-[780px]'>
                The Community Showcase
                <p className='mt-2 text-[#666e75] text-[16px] max-w [500px]'>
                    Browse through a collection of imaginitive and visually 
                    stunning images generated by ORION AI.
                </p>

            </h1>
        </div>
        {isSearchVisible && (
        <div className='mt-0'> 
            <FormField 
            labelName='Search posts'
            type='text'
            name='text'
            placeholder='Search posts'
            value={searchText}
            handleChange={handleSearchChange}/>
        </div>
        )}
        <div className='mt-10'>
            {loading ?(
                <div className='flex justify-center items-center'>
                    <Loader/>
                </div>
            ) : (
                <>
                {searchText && (
                    <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                        Showing results for <span className='text-[#222328]'>
                            {searchText}
                        </span>
                    </h2>
                )}
                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grids-cols-1 gap-3'>
                    {searchText ?(
                        <RenderCards data={searchedResults}
                        title='No Search results found'
                        />
                    ):(
                        <RenderCards
                        data={allPosts}
                        title="No Posts found"
                        />
                    )}
                </div>
                </>
            )}
        </div>
        <br />
<div class="w-full min-h-screen flex items-center justify-center bg-black">
        <div class="md:w-2/3 w-full px-4 text-white flex flex-col">
            <div class="w-full text-7xl font-bold">
                <h1 class="w-full md:w-2/3">How can we help you. Get
                    in touch</h1>
            </div>
            <div class="flex mt-8 flex-col md:flex-row md:justify-between">
                <p class="w-full md:w-2/3 text-gray-400">If there are any issues don't hesitate to send a report. Anyone may question an uncited claim if your work has been tagged. You may also check out our other sites below.</p>
                <div class="w-44 pt-6 md:pt-0">
                    <a href="mailto:karthikeyanbalamurugan4@gmail.com?subject=Report on Orion.AI" class="bg-[#FF3383] justify-center text-center rounded-lg shadow px-10 py-3 flex items-center font-inter buton cursor-pointer">Contact US</a>
                </div>
            </div>
            <div class="flex flex-col">
                <div class="flex mt-24 mb-12 flex-row justify-between">
                    <div class="-pt-1">
                        <img src={or} alt="" width="84" height="25" />   
                    </div>
                    <a class="hidden md:block cursor-pointer text-gray-600 hover:text-white uppercase" href='https://your-projects-com.vercel.app/'>YourProjects.com</a>
                    <a class="hidden md:block cursor-pointer text-gray-600 hover:text-white uppercase" href='https://codelingual.vercel.app/'>CodeLingual</a>
                    <a class="hidden md:block cursor-pointer text-gray-600 hover:text-white uppercase" href='https://the-jam.vercel.app/'>The Jams</a>
                    <a class="hidden md:block cursor-pointer text-gray-600 hover:text-white uppercase" href='https://bank-modern-app-frontend.vercel.app/'>HooBank</a>
                    <div class="flex flex-row space-x-8 items-center justify-between">
                        <a href='https://github.com/karth1kkk' className='cursor-pointer' target='__blank'>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-5" width="9" height="15" viewBox="0 0 12 15" >
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                        </svg>                           
                        </a>
                        <a href='https://www.instagram.com/karth1kkk/' target='__blank'>
                            <svg width="12" height="13" viewBox="0 0 12 13" fill="none" xmlns="http://www.w3.org/2000/svg" className='cursor-pointer'>
                                <path d="M5.99536 2.91345C5.17815 2.91345 4.39441 3.23809 3.81655 3.81594C3.2387 4.3938 2.91406 5.17754 2.91406 5.99475C2.91406 6.81196 3.2387 7.5957 3.81655 8.17356C4.39441 8.75141 5.17815 9.07605 5.99536 9.07605C6.81257 9.07605 7.59631 8.75141 8.17417 8.17356C8.75202 7.5957 9.07666 6.81196 9.07666 5.99475C9.07666 5.17754 8.75202 4.3938 8.17417 3.81594C7.59631 3.23809 6.81257 2.91345 5.99536 2.91345ZM5.99536 7.99586C5.46446 7.99586 4.9553 7.78496 4.57989 7.40955C4.20448 7.03415 3.99358 6.52499 3.99358 5.99408C3.99358 5.46318 4.20448 4.95402 4.57989 4.57861C4.9553 4.20321 5.46446 3.99231 5.99536 3.99231C6.52626 3.99231 7.03542 4.20321 7.41083 4.57861C7.78624 4.95402 7.99714 5.46318 7.99714 5.99408C7.99714 6.52499 7.78624 7.03415 7.41083 7.40955C7.03542 7.78496 6.52626 7.99586 5.99536 7.99586Z" fill="white"/>
                                <path d="M9.19863 3.51848C9.59537 3.51848 9.91698 3.19687 9.91698 2.80013C9.91698 2.4034 9.59537 2.08179 9.19863 2.08179C8.8019 2.08179 8.48029 2.4034 8.48029 2.80013C8.48029 3.19687 8.8019 3.51848 9.19863 3.51848Z" fill="white"/>
                                <path d="M11.6821 2.06975C11.5279 1.67138 11.2921 1.30961 10.99 1.00759C10.6879 0.705576 10.326 0.469972 9.92759 0.31586C9.46135 0.140842 8.9688 0.0462069 8.4709 0.0359839C7.82919 0.00799638 7.62594 0 5.99867 0C4.37139 0 4.16282 -6.70254e-08 3.52643 0.0359839C3.02891 0.0456842 2.53671 0.140339 2.07108 0.31586C1.67255 0.469792 1.31059 0.705333 1.00844 1.00737C0.706289 1.30941 0.47061 1.67127 0.316526 2.06975C0.141474 2.53595 0.0470554 3.02855 0.0373167 3.52643C0.00866281 4.16748 0 4.37072 0 5.99867C0 7.62594 -4.96485e-09 7.83319 0.0373167 8.4709C0.0473123 8.96935 0.14127 9.46113 0.316526 9.92825C0.471042 10.3266 0.70695 10.6883 1.00918 10.9903C1.3114 11.2923 1.6733 11.5279 2.07175 11.6821C2.5365 11.8642 3.0289 11.9656 3.52777 11.982C4.16948 12.01 4.37272 12.0187 6 12.0187C7.62728 12.0187 7.83585 12.0187 8.47223 11.982C8.97008 11.9719 9.46262 11.8775 9.92892 11.7028C10.3272 11.5483 10.689 11.3125 10.9911 11.0104C11.2932 10.7083 11.529 10.3466 11.6835 9.94825C11.8587 9.48179 11.9527 8.99 11.9627 8.49156C11.9913 7.85051 12 7.64727 12 6.01932C12 4.39138 12 4.18481 11.9627 3.54709C11.9549 3.04216 11.86 2.54237 11.6821 2.06975ZM10.8705 8.42159C10.8662 8.80562 10.7961 9.18608 10.6633 9.54642C10.5632 9.80555 10.41 10.0409 10.2135 10.2372C10.017 10.4336 9.78162 10.5867 9.52243 10.6866C9.16608 10.8188 8.78967 10.8889 8.4096 10.8938C7.77654 10.9231 7.59796 10.9305 5.97468 10.9305C4.35007 10.9305 4.18414 10.9305 3.53909 10.8938C3.15921 10.8892 2.78298 10.8191 2.42692 10.6866C2.16683 10.5873 1.93048 10.4345 1.73316 10.2381C1.53584 10.0417 1.38194 9.80605 1.28143 9.54642C1.15045 9.18995 1.08039 8.81398 1.07419 8.43425C1.04554 7.8012 1.03887 7.62261 1.03887 5.99933C1.03887 4.37539 1.03887 4.20946 1.07419 3.56375C1.0785 3.17993 1.14859 2.7997 1.28143 2.43958C1.48467 1.91382 1.90116 1.5 2.42692 1.29876C2.78316 1.16691 3.15928 1.09682 3.53909 1.09151C4.17281 1.06286 4.35073 1.05486 5.97468 1.05486C7.59862 1.05486 7.76522 1.05486 8.4096 1.09151C8.7897 1.09609 9.16617 1.1662 9.52243 1.29876C9.7816 1.39889 10.017 1.55211 10.2134 1.74858C10.4099 1.94504 10.5631 2.18041 10.6633 2.43958C10.7942 2.79606 10.8643 3.17203 10.8705 3.55175C10.8992 4.18547 10.9065 4.36339 10.9065 5.98734C10.9065 7.61062 10.9065 7.78521 10.8778 8.42226H10.8705V8.42159Z" fill="white"/>
                            </svg>    
                        </a>
                        <a href="www.linkedin.com/in/karthikeyan-bala-murugan-b5b55b266" target='__blank'>
                        <svg width={14} height={14} viewBox="0 0 14 14" className="fill-current">
                            <path d="M13.0214 0H1.02084C0.453707 0 0 0.451613 0 1.01613V12.9839C0 13.5258 0.453707 14 1.02084 14H12.976C13.5432 14 13.9969 13.5484 13.9969 12.9839V0.993548C14.0422 0.451613 13.5885 0 13.0214 0ZM4.15142 11.9H2.08705V5.23871H4.15142V11.9ZM3.10789 4.3129C2.42733 4.3129 1.90557 3.77097 1.90557 3.11613C1.90557 2.46129 2.45002 1.91935 3.10789 1.91935C3.76577 1.91935 4.31022 2.46129 4.31022 3.11613C4.31022 3.77097 3.81114 4.3129 3.10789 4.3129ZM11.9779 11.9H9.9135V8.67097C9.9135 7.90323 9.89082 6.8871 8.82461 6.8871C7.73571 6.8871 7.57691 7.74516 7.57691 8.60323V11.9H5.51254V5.23871H7.53154V6.16452H7.55423C7.84914 5.62258 8.50701 5.08065 9.52785 5.08065C11.6376 5.08065 12.0232 6.43548 12.0232 8.2871V11.9H11.9779Z" />
                        </svg>                           
                        </a>
                    </div>
                </div>
                <hr class="border-gray-600"/>
                <p class="w-full text-center my-12 text-gray-600">Copyright © 2023 Orion.AI</p>
            </div>
        </div>
    </div>
    </section>
  )
}

export default Home

